version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ametist_astralys_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: usuario
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: ametist_astralys_api
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://root:1234@db:3306/usuario
      SECRET_KEY: segredo-super-secreto-ms-identity
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
